config/routes.rb
Rails.application.routes.draw do

  get 'post/index'
  root 'pages#home'
  get 'pages/about_us'
  get 'pages/contact'
  get 'hello/:name', to: 'pages#hello', as: 'hello'
  get 'post/index' as: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "mi_layout", only: [:hello]

  def home
  end

  def hello
    @name = params[:name]
  end

  def about_us
    @greeting = "What is Lorem Ipsum?
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
  end
  
  def contact
    @contact = ["Calle Falsa 123", 05742351351]
  end

  def posts
    @posts = "Where can I get some?
    There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc."
  end

end

app/controllers/post_controller.rb
class PostController < ApplicationController
  
  def index
    @post = Post.all
    redirect_to hello_path('Sebas')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/mi_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Mi Layout</h1>
    <ul> 
      <li><%= link_to "Hello", hello_url('Sebastian')%></li>
      # <li><a href="<%= pages_contact_path %>">Contact</a></li>
      # <li><a href="<%= pages_posts_path %>">Posts</a></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>About Us</h1>
    <%= @greeting %>

app/views/pages/contact.html.erb
<h1>Contact</h1>
    <%= @contact %>

app/views/pages/hello.html.erb
<h1>Wellcome <%= @name %></h1>

app/views/pages/home.html.erb
<h1>Pages#home(Sebastian)</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/posts.html.erb
<h1>Posts</h1>
    <%= @posts %>

app/views/post/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>